### ISSUE TITLE
Uploading additional files does not work

### ISSUE THREAD

**Issue by snake66** [espebra/filebin#11]
Selecting *more -> Upload files* from an existing bin lets me select a new file, and it seems the file is uploeaded (there's a progress bar, but the file does not show up in the bin.

**Comment by espebra** [comment]
Hi,
Thanks for the report, I'm going to assume this is on [filebin.net](https://filebin.net).

I'm not able to reproduce this particular problem now, and at this point I think that the problem is (was) related to some maintenance work that was ongoing in the frontend layer at approximately the same time. This is a feature that I've used a lot, so I'd be a bit surprised if it turns out to be an actual bug.

Do you remember if the progress bar(s) turned green? If that is the case, it means that the upload(s) completed with a 200/201 response code from the web service - and this only happens on success after lots of verification. Any other return code will make the progress bars turn red, indicating that an error occurred.

I suggest the following next steps:

1. You see if you are able to reproduce the problem.
2. If successful to reproduce, please let me know the bin id here or by email (if the content of the bin is private) and I'll have a closer look.

**Comment by snake66** [comment]
Hey, thanks for the response! Yes the progress bars turned green, and checking back on the URI now the file is there as it should. Possibly a caching issue. I'll close this for now and report back if I see something strange again.

**Comment by espebra** [comment]
Hi again @snake66,
Finally I managed to hit this bug as well, which I (really) should have discovered way earlier.

The problem was that cache invalidation requests were not allowed from the IPv6 address of the instance, and - yes - filebin tried to send cache invalidation requests from its IPv6 address.

**Comment by snake66** [comment]
Awesome! :)
