### ISSUE TITLE
Concurrent filebins in docker...

### ISSUE THREAD

**Issue by cconstab** [espebra/filebin#29]
Not sure how well Filebin scales. So was thinking to dockerize and run multiple filebin binaries all pointing back to the same underlying file system in either k8s or swarm.

 Seemed like a good idea as I could scale horizontally by adding more containers and provide high resiliency.

But although everything sorta works state is/seems to be kept in memory as well as the underlying filesystem. Could you confirm?

Happy to work on a solution to this, but would welcome your point of view.

**Comment by cconstab** [comment]
Looks like filebin2 is a good starting point, sorry missed that repo in the previous issue.
Still would welcome your comments

Thanks

**Comment by espebra** [comment]
Hi,

Filebin is designed to run with as few dependencies as possible for easy setup and maintenance. Initially all operations were done against the filesystem. It worked, but got slow as the number of bins and files increased. To mitigate this, I added an in-memory meta data cache (just some data structures with mutexes) to speed up the various read/query operations. This meta data cache will most likely be a complete show stopper for your multi instance/horizontal design by the way, and it is also the reason for why starting up filebin takes so long time.

The current design of filebin leaves something to be desired, for me at least. At the end of the day, not having a proper database in place is pretty limiting. It is nice to not have a database from an installation and maintenance point of view, but it come with a cost (performance, horizontal scalability and lack of flexibility/persistent history). In order to fix this, I started working on filebin2 in a new repository. Filebin2 is based on PostgreSQL (for meta data) and S3 (for file storage) and should scale horizontally just fine. I haven't tested it, but I have no reason to believe it won't work. A word of warning though - it is work in progress still, so things may change.

**Comment by cconstab** [comment]
Thanks for all the detail.. I will take a look at filebin2!

Thanks so much

**Comment by cconstab** [comment]
Oh and report back how it goes!

**Comment by cconstab** [comment]
Fantastic thanks!

**Comment by espebra** [comment]
I've updated the [readme](https://github.com/espebra/filebin2/blob/master/README.md) now. I'll respond to https://github.com/espebra/filebin2/issues/8 and close this.
